[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "wujihandpy"
version = "0.0.2"
description = "Python bindings for WujiHandCpp"
authors = [{name = "Wuji Technology <support@pan-motor.com>"}]
dependencies = []
